Readme

* By lixf
* Result in 'processed/Q1a_res.xlsx'

In [27]:
import pandas as pd
from tqdm import *
import os
import math
from datetime import timedelta

In [28]:
tab1 = pd.read_excel('metadata/表1-患者列表及临床信息.xlsx')
tab1 = tab1.rename(columns={'Unnamed: 0': 'ID'})

In [29]:
tab1['发病到首次影像检查时间间隔'].describe()

count    160.000000
mean       3.641375
std        4.602256
min        0.250000
25%        1.000000
50%        2.000000
75%        4.000000
max       24.000000
Name: 发病到首次影像检查时间间隔, dtype: float64

In [30]:
tab2_dict = {}
for i, sheet_name in enumerate(['首次', '随访1', '随访2', '随访3', '随访4', '随访5', '随访6', '随访7', '随访8']):
    if sheet_name == '首次':
        col = '首次检查流水号'
    else:
        col = sheet_name + '流水号'

    tab2_dict[i] = pd.read_excel('metadata/表2-患者影像信息血肿及水肿的体积及位置.xlsx', sheet_name=sheet_name, usecols=['ID', col, 'HM_volume'])

是否发生血肿扩张可根据血肿体积前后变化，具体定义为：后续检查 比首次检查绝对体积增加≥6 mL 或相对体积增加≥33%

In [31]:
'''计算在哪一次开始发生血肿扩张'''
tab2_cmp = pd.DataFrame()
tab2_cmp['ID'] = tab2_dict[0]['ID']
tab2_cmp['num_0'] = tab2_dict[0]['首次检查流水号']  # 流水号
tab2_cmp['vol_0'] = tab2_dict[0]['HM_volume'] / 1000 # 血肿总体积（ml）

for k in tab2_dict.keys():
    if k == 0:
        continue

    tab2_cmp['num_%d' % k] = tab2_dict[k]['随访%d流水号' % k] # 流水号
    tab2_cmp['vol_%d' % k] = tab2_dict[k]['HM_volume'] / 1000 # 血肿总体积（ml）
    tab2_cmp['abs_%d' % k] = tab2_cmp['vol_%d' % k] - tab2_cmp['vol_0']  # 血肿绝对体积增加
    tab2_cmp['rela_%d' % k] = tab2_cmp['vol_%d' % k] / tab2_cmp['vol_0'] - 1 # 血肿相对体积增加

    tab2_cmp['if_HM_%d' % k] = tab2_cmp.apply(lambda x: 1 if x['abs_%d' % k] >= 6 or x['rela_%d' % k] >= 0.33 else 0, axis=1) # 判断绝对体积增加是否超过6ml或相对体积增加超过33%

In [32]:
tab2_cmp = pd.merge(tab2_cmp, tab1[['ID', '发病到首次影像检查时间间隔']], on='ID', how='left') # 补充发病到首次影像检查时间间隔的数据

In [33]:
'''补充流水号与时间的对应'''
ann_tab = pd.read_excel('metadata/附表1-检索表格-流水号vs时间(1).xlsx')

In [34]:
ann_dict = {} # 获得一个流水号-时间对应的字典
col_list = ann_tab.columns.tolist()
for col in col_list:
    if '流水号' in col:
        print(col, col_list[col_list.index(col) - 1])
        for num, time in zip(ann_tab[col], ann_tab[col_list[col_list.index(col) - 1]]):
            if math.isnan(num): # 无随访记录
                continue
            ann_dict[num] = time

入院首次检查流水号 入院首次检查时间点
随访1流水号 随访1时间点
随访2流水号 随访2时间点
随访3流水号 随访3时间点
随访4流水号 随访4时间点
随访5流水号 随访5时间点
随访6流水号 随访6时间点
随访7流水号 随访7时间点
随访8流水号 随访8时间点
随访9流水号 随访9时间点
随访10流水号 随访10时间点
随访11流水号 随访11时间点
随访12流水号 随访12时间点
随访13流水号 随访13时间点

In [35]:
'''检查一下流水号字典和所有患者的流水号是否对应'''
num_in_tab2 = []
num_in_ann = list(ann_dict.keys())

for col in tab2_cmp.columns:
    if 'num' in col:
        num_in_tab2 += [x for x in tab2_cmp[col] if not math.isnan(x)]

In [36]:
set(num_in_tab2) - set(num_in_ann) # 表2记录中的所有流水号均在附件2中出现

set()

In [37]:
set(num_in_ann) - set(num_in_tab2) # 附件2中记录的一些流水号没有在表2中出现，合理（附件2中最多记录到了第13次随访，而表2最多只有8次）

{20180201000828.0,
 20180213000362.0,
 20180311000567,
 20180313000652.0,
 20180316001622.0,
 20180709001407,
 20180723001587.0,
 20181016000833,
 20181022000765.0,
 20181202000350.0,
 20190106000492,
 20190110001733,
 20190111000143.0,
 20190115002118.0,
 20190521000161,
 20190527001139.0,
 20190531000921,
 20190611002490.0,
 20190703001594,
 20190709002062.0,
 20190717001449,
 20190718000497,
 20190722000063.0,
 20190722001712.0,
 20190727000742,
 20190728000021.0,
 20190803000709,
 20190805000440.0,
 20190902000491,
 20190904000211,
 20190905002111.0,
 20190907000580,
 20190910001871,
 20190911000935.0,
 20190916001924.0,
 20190916001966.0,
 20190918000218,
 20190923001872.0,
 20190925001011,
 20191005000359.0,
 20191005000659,
 20191006000601,
 20191009002104.0,
 20191014000993.0,
 20191025001949,
 20191028002410,
 20191029000516,
 20191031000088.0,
 20191031000191,
 20191102000588.0,
 20191104000927.0,
 20191106000679.0,
 20191112001920,
 20191115001582.0,
 20191127000745,
 20191128000807,
 20191202001041.0,
 20191203001049.0,
 20191209001666,
 20191216001389.0,
 20191224002118,
 20191228000911,
 20191230001063.0,
 20191230001175.0}

In [38]:
'''获取每个人每次体检到首次影像时间'''
for col in tab2_cmp.columns:
    if 'num' in col:
        i = int(col.replace('num_', ''))
        tab2_cmp['time_%d' % i] = tab2_cmp[col].map(lambda x: ann_dict[x] if x in ann_dict.keys() else None)

        if i != 0:  
            # 计算当次随访时间到发病时间的间隔（注意：是当次随访时间-首次检查时间+发病到首次影像检查时间间隔）
            # 转换时间格式
            tab2_cmp['interval_%d' % i] = tab2_cmp.apply(lambda x: (x['time_%d' % i] - x['time_0']).total_seconds() / 3600 + x['发病到首次影像检查时间间隔'], axis=1)

In [39]:
tab2_cmp.to_excel('processed/Q1a_record.xlsx', index=False)

In [40]:
'''
保留最主要的列
- 当次检测结果是否血肿扩张
- 当次检测时间到发病时间的间隔
'''
tab2_HM = tab2_cmp[['ID'] + ['if_HM_%d' % i for i in range(1, 9)] + ['interval_%d' % i for i in range(1, 9)]][:100] # 只需计算前100人

In [41]:
tab2_HM['是否发生血肿扩张'] = None
tab2_HM['血肿扩张时间'] = None

for i, row in tab2_HM.iterrows():
    for j in range(1, 9):
        if row['if_HM_%d' % j] == 1 and row['interval_%d' % j] <= 48:
            tab2_HM.loc[i, '是否发生血肿扩张'] = 1
            tab2_HM.loc[i, '血肿扩张时间'] = row['interval_%d' % j]
            break

        else:
            tab2_HM.loc[i, '是否发生血肿扩张'] = 0

In [42]:
tab2_HM

,ID,if_HM_1,if_HM_2,if_HM_3,if_HM_4,if_HM_5,if_HM_6,if_HM_7,if_HM_8,interval_1,interval_2,interval_3,interval_4,interval_5,interval_6,interval_7,interval_8,是否发生血肿扩张,血肿扩张时间
0,sub001,0,0,0,0,0,0,0,0,8.268333,132.108333,259.737500,425.538333,NaN,NaN,NaN,NaN,0,None
1,sub002,0,0,0,0,0,0,0,0,14.923333,69.221944,448.016389,1119.191944,NaN,NaN,NaN,NaN,0,None
2,sub003,1,1,0,0,0,0,0,0,9.522500,39.595833,NaN,NaN,NaN,NaN,NaN,NaN,1,9.5225
3,sub004,0,0,0,0,0,0,0,0,16.974167,83.845278,227.501111,NaN,NaN,NaN,NaN,NaN,0,None
4,sub005,1,1,0,0,0,0,0,0,26.467500,97.943056,NaN,NaN,NaN,NaN,NaN,NaN,1,26.4675
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,sub096,0,0,0,0,0,0,0,0,13.761389,87.980278,255.119167,423.501111,595.642778,NaN,NaN,NaN,0,None
96,sub097,0,0,0,0,0,0,0,0,31.925556,171.400278,NaN,NaN,NaN,NaN,NaN,NaN,0,None
97,sub098,1,0,0,0,0,0,0,0,42.756667,187.656944,570.496944,903.368333,NaN,NaN,NaN,NaN,1,42.756667
98,sub099,1,1,0,0,0,0,0,0,17.672778,42.529444,NaN,NaN,NaN,NaN,NaN,NaN,1,17.672778
99,sub100,0,0,0,0,0,0,0,0,34.731111,197.236667,NaN,NaN,NaN,NaN,NaN,NaN,0,None

In [43]:
tab2_HM.to_excel('processed/Q1a_res.xlsx', index=False)